spring:
  data:
    mongodb:
      uri: ${MONGO_DEV_URI}
      database: theboringinvestment
  application:
    name: portfoliobackend
server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  port: 8080
jwt:
  secret: ${JWT_DEV_SECRET}
