# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set gradle
        run: chmod +x gradlew
      - name: build jar
        run: ./gradlew build
      - name: docker build
        run: docker build -t registry.heroku.com/boringinvestmentclub/web .
      - name: docker login
        run: docker login --username=_ --password=${{ secrets.HEROKU_API_KEY }} registry.heroku.com
      - name: docker push
        run: docker push registry.heroku.com/boringinvestmentclub/web
      - name: heroku release
        run: HEROKU_API_KEY='${{ secrets.HEROKU_API_KEY }}' heroku container:release --app boringinvestmentclub web
